=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/MDSIProject/XSD/etablissements.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	xmlns:type="http://insa/mdsi/types">
	
	<xs:import schemaLocation="./types.xsd" namespace="http://insa/mdsi/types"/>

	<xs:element name="etablissements">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entreprise" type="typeEntreprise" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="laboratoire" type="typeLaboratoire" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="typeEtablissement">
		<xs:sequence>
			<xs:element name="nom" type="xs:token"/>
			<xs:element name="adresse" type="xs:token"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="typeEntreprise">
		<xs:complexContent>
			<xs:extension base="typeEtablissement">
				<xs:attribute name="numSIRET" type="type:NumSIRET" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="typeLaboratoire">
		<xs:complexContent>
			<xs:extension base="typeEtablissement">
				<xs:attribute name="unite" type="xs:token" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/MDSIProject/Backup XML/etablissements.xml
<?xml version="1.0" encoding="UTF-8"?>
<etablissements
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./etablissements.xsd">
	
	<entreprise numSIRET="12345678901234">
		<nom>Entreprise1</nom>
		<adresse>Adresse de l'entreprise 1</adresse>
	</entreprise>
	<entreprise numSIRET="12345678901235">
		<nom>Entreprise2</nom>
		<adresse>Adresse de l'entreprise 2</adresse>
	</entreprise>
	<laboratoire unite="CNRS">
		<nom>Labo1</nom>
		<adresse>Adresse du labo 1</adresse>
	</laboratoire>
	<laboratoire unite="Laas">
		<nom>Labo2</nom>
		<adresse>Adresse du labo 2</adresse>
	</laboratoire>
</etablissements>
