=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/MDSIProject/XSD/etudiants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	xmlns:type="http://insa/mdsi/types">
	
	<xs:import schemaLocation="./types.xsd" namespace="http://insa/mdsi/types"/>
	
	<xs:element name="etudiants">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="etudiant" type="typeEtudiant" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="typeEtudiant">
		<xs:sequence>
			<xs:element name="nom" type="xs:token"/>
			<xs:element name="prenom" type="xs:token"/>
			<xs:element name="dateDeNaissance" type="xs:date"/>
		</xs:sequence>
		<xs:attribute name="numEtudiant" type="type:NumEtudiant" use="required"/>
	</xs:complexType>
</xs:schema>

=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/MDSIProject/Backup XML/etudiants.xml
<?xml version="1.0" encoding="UTF-8"?>
<etudiants
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./etudiants.xsd">
	
	<etudiant numEtudiant="3300111">
		<nom>NomEtudiant1</nom>
		<prenom>PrenomEtudiant1</prenom>
		<dateDeNaissance>1990-10-10</dateDeNaissance>
	</etudiant>
	<etudiant numEtudiant="3300112">
		<nom>NomEtudiant2</nom>
		<prenom>PrenomEtudiant2</prenom>
		<dateDeNaissance>1990-10-10</dateDeNaissance>
	</etudiant>
</etudiants>
