=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/MDSIProject/XSD/personnels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	xmlns:type="http://insa/mdsi/types">
	
	<xs:import schemaLocation="./types.xsd" namespace="http://insa/mdsi/types"/>
	
	<xs:element name="personnels">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="personnel" type="typePersonnel" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="typePersonnel">
		<xs:sequence>
			<xs:element name="nom" type="xs:token"/>
			<xs:element name="prenom" type="xs:token"/>
			<xs:element name="fonction" type="xs:token"/>
			<xs:element name="mail" type="type:Mail" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="tel" type="type:Tel" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="codePersonnel" type="type:CodePersonnel" use="required"/>
	</xs:complexType>
</xs:schema>

=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/MDSIProject/Backup XML/personnels.xml
<?xml version="1.0" encoding="UTF-8"?>
<personnels
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./personnels.xsd">
	
	<personnel codePersonnel="1erCodePersonnel">
		<nom>NomPerso1</nom>
		<prenom>PrenomPerso1</prenom>
		<fonction>FonctionPerso1</fonction>
		<mail>MailPerso1@insa-toulouse.fr</mail>
		<mail>MailPerso1@laas.fr</mail>
		<tel>+331234567</tel>
		<tel>01234567</tel>
	</personnel>
	<personnel codePersonnel="2emeCodePersonnel">
		<nom>NomPerso2</nom>
		<prenom>PrenomPerso2</prenom>
		<fonction>FonctionPerso2 FonctionPerso2-2</fonction>
		<mail>MailPerso2@insa-toulouse.fr</mail>
		<mail>MailPerso2@laas.fr</mail>
	</personnel>
	<personnel codePersonnel="3emeCodePersonnel">
		<nom>NomPerso3</nom>
		<prenom>PrenomPerso3</prenom>
		<fonction>FonctionPerso3</fonction>
	</personnel>
	<personnel codePersonnel="4emeCodePersonnel">
		<nom>NomPerso4</nom>
		<prenom>PrenomPerso4</prenom>
		<fonction>FonctionPerso4</fonction>
	</personnel>
	<personnel codePersonnel="5emeCodePersonnel">
		<nom>NomPerso5</nom>
		<prenom>PrenomPerso5</prenom>
		<fonction>FonctionPerso5</fonction>
	</personnel>
</personnels>
