=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/MDSIProject/XSD/rapports.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	xmlns:type="http://insa/mdsi/types">

	<xs:import schemaLocation="./types.xsd" namespace="http://insa/mdsi/types"/>

	<xs:element name="rapports">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="rapport" type="typeRapport" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="typeRapport">
		<xs:sequence>
			<xs:element name="intitule" type="xs:token"/>
			<xs:element name="note" type="type:Note"/>
			<xs:element name="soutenance" type="xs:token" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="codeRapport" type="xs:token" use="required"/>
	</xs:complexType>
</xs:schema>

=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/MDSIProject/Backup XML/rapports.xml
<?xml version="1.0" encoding="UTF-8"?>
<rapports
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./rapports.xsd">
	
	<rapport codeRapport="rapport1">
		<intitule>Modelisation Systemes Concurrents</intitule>
		<note>12</note>
		<soutenance>StageLaas</soutenance>
	</rapport>
	<rapport codeRapport="rapport2">
		<intitule>Modelisation Systeme Information</intitule>
		<note>15</note>
	</rapport>
</rapports>
