=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/MDSIProject/XSD/stages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	xmlns:type="http://insa/mdsi/types">

	<xs:import schemaLocation="./types.xsd" namespace="http://insa/mdsi/types"/>

	<xs:element name="stages">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="stage" type="typeStage" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="typeStage">
		<xs:sequence>
			<xs:element name="intitule" type="xs:token"/>
			<xs:element name="annee" type="xs:gYear"/>
			<xs:element name="duree" type="xs:duration"/>
			<xs:element name="enseignant" type="type:CodePersonnel" minOccurs="1" maxOccurs="1"/>
			<xs:element name="encadrant" type="type:CodePersonnel" maxOccurs="unbounded"/>
			<xs:element name="motCle" type="xs:token" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="codeStage" type="xs:token" use="required"/>
		<xs:attribute name="etudiant" type="xs:unsignedInt" use="required"/>
		<xs:attribute name="PO" type="xs:token" use="required"/>
		<xs:attribute name="rapport" type="xs:token" use="required"/>
		<xs:attribute name="evaluation" type="xs:token" use="required"/>
	</xs:complexType>
</xs:schema>

=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/MDSIProject/Backup XML/stages.xml
<?xml version="1.0" encoding="UTF-8"?>
<stages
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./stages.xsd">
	
	<stage stage="laas-3300111-2016" etudiant="3300111"
		PO="4IR" rapport="rapport1" evaluation="EvaluationStageLaas">

		<intitule>Modelisation Systeme Information</intitule>
		<duree>P3M5D</duree>
		<annee>2016</annee>
		<enseignant>2emeCodePersonnel</enseignant>
		<encadrant>4emeCodePersonnel</encadrant>
		<motCle>Modelisation</motCle>
		<motCle>Systeme</motCle>
	</stage>
	<stage stage="CNRS-3300111-2015" etudiant="3300111"
		PO="4IR" rapport="rapport2" evaluation="EvaluationStage2">
		
		<intitule>Modelisation Systemes Concurrents</intitule>
		<duree>P3M5D</duree>
		<annee>2015</annee>
		<enseignant>1erCodePersonnel</enseignant>
		<encadrant>3emeCodePersonnel</encadrant>
		<motCle>Modelisation</motCle>
		<motCle>Systeme</motCle>
		<motCle>Concurrent</motCle>
	</stage>
</stages>
