=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/xmldtd/validation2.dtd
<!ELEMENT universite (allcours, professeurs)>
<!ELEMENT allcours (cours+)>
<!ELEMENT cours (titre, evaluation)>
<!ATTLIST cours idc ID #REQUIRED>
<!ATTLIST cours enseignant IDREF #IMPLIED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT evaluation (#PCDATA)>
<!ATTLIST evaluation score CDATA #REQUIRED>
<!ELEMENT professeurs (professeur+)>
<!ELEMENT professeur EMPTY>
<!ATTLIST professeur idp ID #REQUIRED>
<!ATTLIST professeur cours IDREFS #REQUIRED>

=== yuxiaomao/INSA_desktop_ymao/4Y1S/MDSI/xmldtd/validation2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universite SYSTEM "validation2.dtd">
<universite>
  <allcours>
    <cours idc="c1" enseignant="p1">
      <titre>Maths</titre>
      <evaluation score="15">blablabla</evaluation>
    </cours>
     <cours idc="c2">
      <titre>Physique</titre>
      <evaluation score="12">blablabla2</evaluation>
    </cours>
  </allcours>
  <professeurs>
    <professeur idp="p1" cours="c1 c2"/>
    <professeur idp="p2" cours="c2"/>
  </professeurs>
</universite>
