<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cdtheque [
  <!ELEMENT cdtheque (cd*)>
  <!ATTLIST cdtheque date CDATA #REQUIRED>
  <!ATTLIST cdtheque auteur CDATA #REQUIRED>
  <!ELEMENT cd (titre,artiste,style?)>
  <!ELEMENT titre (#PCDATA)>
  <!ELEMENT style (#PCDATA)>
  <!ELEMENT artiste (#PCDATA)>
]>
<cdtheque date="12/2015" auteur="a1">
  <cd>
    <titre>t1</titre>
    <artiste>ar1</artiste>
    <style>s1</style>
  </cd>
  <cd>
    <titre>t2</titre>
    <artiste>ar1</artiste>
  </cd>
  <cd>
    <titre>t2</titre> 
    <artiste>ar1</artiste>
    <style/>
  </cd>
  
</cdtheque>
